version: '3.4'

services:


  movieservice.api:
    image: ${DOCKER_REGISTRY-}movieserviceapi
    build:
      context: .
      dockerfile: MovieService/MovieService.Api/Dockerfile
    ports:
     - "8000:80"

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017 
    volumes:
     - mongodb-data:/data/db

  rabbitmq:
     image: rabbitmq:3-management
     container_name: rabbitmq
     ports:
            - 15672:15672

  redisdb:
    image: "redis:alpine"
    container_name: redisdb
    ports:
     - "6379:6379"
   

volumes:
  mongodb-data:
    external: false
