version: '3.4'

services:
  movieservice.api:
    image: ${DOCKER_REGISTRY-}movieserviceapi
    build:
      context: .
      dockerfile: MovieService/MovieService.Api/Dockerfile

  mongodb-movieservice:
    image: mongo:latest
    container_name: mongodb-movieservice
    ports:
      - 27017:27017 
    volumes:
     - mongodb-movieservice:/data/db

  rabbitmq:
     image: rabbitmq:latest
     container_name: rabbitmq
     volumes:
            - mongodb-movieservice:/var/lib/rabbitmq/mnesia 
     ports:
            - 15672:15672

  redis-movieservice:
    image: "redis:alpine"
    container_name: redis-movieservice
    ports:
     - "6379:6379"
    volumes:
     - ./data/redis-data:/var/lib/redis

volumes:
  mongodb-movieservice:
    external: false
  rabbitmq-movieservice:
    external: false
